import './globals.css'
import type { Metadata } from 'next';
import { Providers } from './GlobalRedux/provider';
import { Inter, Roboto, Caveat} from 'next/font/google'

const inter = Inter({ subsets: ['latin'] });
const caveat = Caveat ({
  subsets: ['latin'],
  weight: ['600','400', '500','700'], 
});
const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['300','400', '500','700'], 
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  
}) {
  return (
    <html lang="en">
    <Providers>
      <body className={caveat.className}>{children}</body>
      </Providers>
    </html>
  )
}
